title: crk
email: charlesrichardking@gmail.com
description: >-
  A dumb little website to show my dumb little projects.

baseurl: "" # the subpath of your site, e.g. /blog
url: localwww.charlesrichardking.com # this is the local URL. This gets overwritten in a production build
github_username:  cking0987
repository: cking0987/crk

logo: "/assets/images/crk_logo.png"
atom_feed:
  hide: true

# Build settings
plugins:
  - jekyll-feed